<?php
/**
 * @file
 *
 * using hook_update
 */

/**
 * Implements hook_update()
 */
function multisite_update_7201() {
  $site_name = $_SERVER['SERVER_NAME'];

  if ($site_name == 'drupal-site.naz') {
    variable_set('my_custom_sitename ', 0);
  }
  else if ($site_name == 'site1.naz') {
    variable_set('my_custom_sitename ', 1);
  }
  else if ($site_name == 'site2.naz') {
    variable_set('my_custom_sitename ', 2);
  }
}
